### ISSUE TITLE
Compatibility with VMOS and other virtualization Software

### ISSUE THREAD

**Issue by ghost** [nexus-projects/nexus_kernel_xiaomi_lmi#1]
Hello,

I previously mentioned this Issue in the telegram support group.
As i have said before, i cannot run a virtual machine for example with the app called vmos on my phone with nexus v9 kernel installed.
With the Quantic kernel installed it works flawlessly.
The logcat is provided as an attached file. I hope you can fix the issue and i could help.

Greetings 
Clasher aka Gabriel on Telegram
[logcat_10-18-2021_19-05-26.txt](https://github.com/nexus-projects/nexus_kernel_xiaomi_lmi/files/7367324/logcat_10-18-2021_19-05-26.txt)

**Comment by akirasupr** [comment]
@Clasher31HD @NotZeetaa behen

**Comment by NotZeetaa** [comment]
@NotZeetaa Wait wtf

**Comment by NotZeetaa** [comment]
> Hello,
> 
> I previously mentioned this Issue in the telegram support group. As i have said before, i cannot run a virtual machine for example with the app called vmos on my phone with nexus v9 kernel installed. With the Quantic kernel installed it works flawlessly. The logcat is provided as an attached file. I hope you can fix the issue and i could help.
> 
> Greetings Clasher aka Gabriel on Telegram [logcat_10-18-2021_19-05-26.txt](https://github.com/nexus-projects/nexus_kernel_xiaomi_lmi/files/7367324/logcat_10-18-2021_19-05-26.txt)

I will see it later
As u mentioned in support group u found probally a solution for the issue

**Comment by ghost** [comment]
Vmos still not working in v10 of Nexus
